accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup")
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home"))
    ),
    path("accounts/", include("accounts.urls"))
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    AccountCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,

)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(),
         name="list_categories"),
    path("accounts/", AccountListView.as_view(),
         name="list_account"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(),
         name="create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account")
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name="categories", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(User, related_name="accounts", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from cmath import log
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib import messages


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # user = form.save(commit=False)  # we save the form because we want
            # to access the user object 
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.username = user.username.lower()
            user.save()
            login(request, user)  # when a user registers, they are
            # automatically logged in after
            return redirect("home")
        else:
            messages.error(
                request, 'An error occurred during the registration.'
                )
    else:
        form = UserCreationForm()
    
    return render(request, 'registration/signup.html', {'form': form})

receipts/views.py
# from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from receipts.models import ExpenseCategory, Receipt, Account
# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    template_name = "receipts/create.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/list_category.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "receipts/create_category.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    fields = ["name", "number"]
    template_name = "receipts/create_account.html"
    
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Home Page</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'list_account' %}">Account</a>
                        </li>
                        <li>
                            <a href="{% url 'create_account' %}">Create Account</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'create_receipt' %}">Create Receipt</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'create_category' %}">Create Category</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated == False %}
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/receipts/account_list.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>Accounts</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number</th>
                        <th>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in account_list %}
                    <tr>
                        <td>{{account.name}}</td>
                        <td>{{account.number}}</td>
                        <td>{{account.receipts.all|length}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post" action="">
                {% csrf_token %}
                {{form.as_p}}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/create_account.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post" action="">
                {% csrf_token %}
                {{form.as_p}}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/create_category.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends "base.html" %}
{% block content %}
  <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
              <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
              </tr>
            </thead>
            <tbody>
              {% for receipt in receipt_list %}
                <tr>
                  <td>{{receipt.vendor}}</td>
                  <td>{{receipt.total}}</td>
                  <td>{{receipt.tax}}</td>
                  <td>{{receipt.date|date:'m-d-Y'}}</td>
                  <td>{{receipt.category}}</td>
                  <td>{{receipt.account}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
  </main>
{% endblock content %}

receipts/templates/receipts/list_category.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>Categories</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in expensecategory_list %}
                    <tr>
                        <td> {{category.name}} </td>
                        <td> {{category.receipts.all|length}} </td>
                    </tr>
                    {% endfor %}
                    <a href="{% url 'create_category' %}">Create</a>
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}